### ISSUE TITLE
AFter, Ctrl F5 runs into error

### ISSUE THREAD

**Issue by gsalvacruz** [johnmcraig/TrelloClone#1]
Microsoft.Data.Sqlite.SqliteException: 'SQLite Error 1: 'no such table: Boards'.'

**Comment by johnmcraig** [comment]
Thank you @gsalvacruz  for opening this issue.

I was able to replicate the error. The `MigrateAsync()` method in the main `Program.cs` is not actually creating a migration to scaffold the database and tables as expected.

This will require further research into debugging the issue. This is happening in another application of mine using the same technique, but a workaround was to us Entity Framework Core command line tools to scaffold a migration. For example, in a terminal:
`dotnet ef migrations add InitialCreate -o .\Data\`

I'll be researching this issue over the weekend, but will probably add the same workaround so the project has an available migration later tonight.

**Comment by johnmcraig** [comment]
Went ahead and implemented the work around by adding a pre-configured migration in the Data folder of the applications' file structure. This will hopefully be a temporary fix (knock on wood).

**Comment by johnmcraig** [comment]
The issue has now been resolved. The `MigrateAsync()` method found in the Main method of the `Program.cs` class has been refactored into an extension method. This was a problem with async/await in the Main method, but the rest of the application being synchronous.
